### ISSUE TITLE
Typing fast in terminal makes Atom lag / hang.

### ISSUE THREAD

**Issue by Superdanby** [facebook-atom/atom-ide-ui#211] opened 2018-04-18 13:34 UTC
### Description
Atom lags / hangs when typing quickly in atom-ide-terminal.

### Expected Behavior
No lags, works smoothly.

### Actual Behavior
Atom hangs there for a moment or even stops working.

### Versions
* Atom: 1.25.1
* Client OS: Fedora 28 Beta
* atom-ide-ui: 0.11.0

### Additional Details
* Installed packages (`apm ls --installed`):
├── Hydrogen@2.4.1
├── activate-power-mode@2.7.0 (disabled)
├── atom-ide-ui@0.11.0
├── autoclose-html@0.23.0
├── autocomplete-clang@0.11.4
├── autocomplete-python@1.10.5
├── busy-signal@1.4.3
├── color-picker@2.3.0
├── file-icons@2.1.18
├── fonts@3.0.3
├── git-plus@7.10.2
├── git-time-machine@1.5.9
├── highlight-selected@0.13.1
├── ide-bash@1.0.11
├── ide-cpp@0.0.3
├── ide-css@0.3.0
├── ide-flowtype@0.22.1
├── ide-html@0.4.2
├── ide-java@0.8.3
├── ide-json@0.2.1
├── ide-php@0.7.14
├── ide-python@0.9.2
├── ide-typescript@0.7.6
├── intentions@1.1.5
├── linter@2.2.0
├── linter-flake8@2.3.0
├── linter-gcc@0.7.1
├── linter-javac@1.9.4
├── linter-markdown@5.2.0
├── linter-ui-default@1.7.1
├── markdown-themeable-pdf@1.2.1
├── markdown-writer@2.7.3
├── minimap@4.29.8
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-linter@2.1.3
├── pdf-view@0.69.0
├── restart-atom@0.2.0
├── split-diff@1.5.2
├── sunset@1.2.1
├── sync-settings@0.8.6
├── teletype@0.12.2
└── youtube-pane@2.0.0

**Comment by pelmers** [comment] 2018-04-19 16:54
Hi @Superdanby , I haven't seen this locally. Does lag happen when using a desktop-native terminal window? It would be most helpful if you could profile atom when it's happening: https://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance

**Comment by Superdanby** [comment] 2018-04-20 03:12
No, Gnome terminal works fine. Here are the profiles, [CPU-20180420T1.zip](https://github.com/facebook-atom/atom-ide-ui/files/1930505/CPU-20180420T1.zip).
It seems that the drawImage function is taking a lot of time. Hope this helps. :smiley:

**Comment by pelmers** [comment] 2018-04-23 16:54
thanks for the cpu profiles! they look very similar to the ones posted in https://github.com/xtermjs/xterm.js/issues/1347, which is most likely caused by upstream bug https://github.com/electron/electron/issues/11051

Since there's not much we can do about the issue here at the moment I will close this one and track the upstream bugs instead.

**Closed by pelmers** 2018-04-23 16:54 UTC
