### ISSUE TITLE
Icons in outline view are not showing up, why? [DUPLICATE]

### ISSUE THREAD

**Issue by gold604** [facebook-atom/atom-ide-ui#180] opened 2018-03-02 21:35 UTC
Hi, icons in the outline view aren't showing up, why? I have expected something like this: https://i.imgur.com/i3eQyvc.png. [This is how it looks in my outline view](https://i.imgur.com/8TWT9EB.png)

Atom-ide-ui v.: 0.9.2
Atom v. : 1.24.0
Electron v.: 1.6.16
Chrome v.: 56.0.2924.87
Node v.: 7.4.0

Packages:
Community Packages (18) C:\Users\user\.atom\packages
├── atom-beautify@0.32.0
├── atom-ide-ui@0.9.2
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── color-picker@2.2.5
├── emmet@2.4.3
├── file-icons@2.1.17
├── highlight-selected@0.13.1
├── ide-java@0.8.1
├── minimap@4.29.8
├── minimap-cursorline@0.2.0
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-pigments@0.2.2
├── pigments@0.40.2
├── platformio-ide-terminal@2.8.0
├── remote-sync@4.1.8
└── sync-settings@0.8.5

Git Packages (1) C:\Users\user\.atom\packages
└── emmet-atom-plugin@0.0.1 (emmetio/atom-plugin#a7b4a447) (disabled)

Thanks.

**Comment by gold604** [comment] 2018-03-02 21:40
Sorry, duplicate....

**Comment by damieng** [comment] 2018-03-02 21:40
Indeed, should be fixed in next update.

Closing as dupe of https://github.com/facebook-atom/atom-ide-ui/issues/175

**Closed by damieng** 2018-03-02 21:40 UTC
