### ISSUE TITLE
Outline View: <li> indentation is larger than expected when having no children

### ISSUE THREAD

**Issue by liuderchi** [facebook-atom/atom-ide-ui#230] opened 2018-04-26 16:08 UTC
### Description

Given 2 list items at same level (having same parent node) _A_ and _B_ with
  - `<li>` _A_ having no children
  - `<li>` _B_ having some children

found that their indentation (or `padding-left`) are not equal.

### Expected Behavior

`<li>` _A_ has same indentation as `<li>` _B_

### Actual Behavior

`padding-left` of `<li>` _A_ is larger than `<li>` _B_

In this example where `<li>` _A_ is `<head>`, `<li>` _B_ is `<body>`

![expected](https://user-images.githubusercontent.com/4994705/39316743-7b7f552a-49ac-11e8-8d87-a2f399e5e935.png)

### Additional Details

- it's found at package [ide-html](https://atom.io/packages/ide-html) with this snippet

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <title>Home</title>
    </head>
    <body>
      <div class=""></div>
    </body>
</html>

```

- Confirmed that HTML Language server parse the HTML correctly after checking debug message from Language server
- When `<head>` having some children, it's applied with style from atom core (`padding-left: 28px;`)

![screen shot 2018-04-26 at 11 17 52 pm](https://user-images.githubusercontent.com/4994705/39317127-6e99f03a-49ad-11e8-9917-8bdfabeeeaee.png)

- However when `<head>` having no children, it's applied [this style from outline-view][style2] (`padding-left: 40px;`)

![screen shot 2018-04-26 at 11 18 15 pm](https://user-images.githubusercontent.com/4994705/39316455-c89719d4-49ab-11e8-891d-8e1044bd3864.png)

### Versions
* Atom: 1.26.0
* Client OS: macOS 10.13.4
* atom-ide-ui: 0.11.1

[style2]: https://github.com/facebook-atom/atom-ide-ui/blob/18b78be63acfb9d5dd8f24a98ea88495506ca2d7/modules/atom-ide-ui/pkg/atom-ide-outline-view/styles/outline-view.less#L39

**Comment by matthewwithanm** [comment] 2018-04-27 20:46
thanks for the report @liuderchi! like @laughedelic mentioned, this is a duplicate of #176 so i'm going to close. this is on @wbinnssmith's radar but he's currently out. i'm sure he would love to come back to a PR though (:

**Closed by matthewwithanm** 2018-04-27 20:46 UTC
