### ISSUE TITLE
Multiple lines 

### ISSUE THREAD

**Issue by Ewwe** [facebook-atom/atom-ide-ui#109] opened 2017-10-31 18:54 UTC
Hi , when i have enabled atom-ui-ide i cant edit or type on multiple lines. I mean when im holding CTRL and then clicking to diferent rows cursor will duplicate and i can type on multiple rows.

### Versions
* Atom: 1.21.2
* Client OS: Windows 10
* atom-ide-ui: 0.53

**Comment by damieng** [comment] 2017-10-31 19:09
Dupe of https://github.com/facebook-atom/atom-ide-ui/issues/61

**Closed by damieng** 2017-10-31 19:09 UTC

**Comment by Ewwe** [comment] 2017-10-31 19:34
Oh sorry
