### ISSUE TITLE
Argument to [path.dirname|path.extname] must be a string

### ISSUE THREAD

**Issue by michael-gracy** [facebook-atom/atom-ide-ui#195] opened 2018-04-02 20:05 UTC
### Before Submitting

* Have you installed an "ide-" language package? atom-ide-ui provides no functionality
  out-of-the box unless you've installed a suitable package.
* If your issue is language-specific, please file an issue against
  the "ide-" language package you're using instead.

### Description
Argument to path.dirname must be a string stack:
Object.dirname - /Users/michael.gracy/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10
Object.lint - /Users/michael.gracy/.atom/packages/linter-shellcheck/lib/main.js:61:24
a.factory - /Users/michael.gracy/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:263:42
a._callFactory - /Users/michael.gracy/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:107:23
a.tryDefer - /Users/michael.gracy/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106:442
new a - /Users/michael.gracy/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106:383

Argument to path.extname must be a string stack:
Object.extname - /Users/michael.gracy/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:20:10
Object.lint - /Users/michael.gracy/.atom/packages/linter-shellcheck/lib/main.js:55:28
a.factory - /Users/michael.gracy/.atom/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:263:42
a._callFactory - /Users/michael.gracy/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:107:23
a.tryDefer - /Users/michael.gracy/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106:442
new a - /Users/michael.gracy/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106:383

### Expected Behavior
No error message

### Actual Behavior
Get above error message after auto-update of atom-ide-ui

### Versions
* Atom: 1.25.0
* Client OS: MacOS 10.12.6
* atom-ide-ui: 0.9.4

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (74) /Users/michael.gracy/.atom/packages
├── Sublime-Style-Column-Selection@1.7.4
├── atom-autocomplete-php@0.25.6 (disabled)
├── atom-ide-ui@0.9.4
├── atom-json-editor@0.4.1
├── atom-package-sync@0.2.6
├── atom-shell-commands@1.5.0
├── atom-typescript@12.3.8 (disabled)
├── autocomplete-ansible@0.1.18
├── autocomplete-bash-builtins@0.3.5
├── autocomplete-json@5.5.2
├── autocomplete-python@1.10.5
├── background-tips@0.28.0 (disabled)
├── busy-signal@1.4.3
├── code-annotations@2.1.3 (disabled)
├── dash@1.7.1
├── dash-on-cursor-active@0.1.2
├── file-icons@2.1.18
├── file-types@0.5.5
├── fold-lines@0.2.2
├── git-blame@1.6.0
├── git-diff-details@1.4.0
├── git-plus@7.10.2
├── git-time-machine@1.5.9
├── go-debug@1.6.0 (disabled)
├── go-plus@5.8.2 (disabled)
├── go-signature-statusbar@1.2.3 (disabled)
├── gotests@0.3.1 (disabled)
├── hyperclick@0.1.5 (disabled)
├── ide-go@0.7.0 (disabled)
├── ide-json@0.2.1
├── ide-python@0.9.2
├── intentions@1.1.5
├── json-colorer@1.0.0
├── json-generator@0.1.15
├── jsonlint@1.1.4
├── language-ansible@0.2.2
├── language-gfm@0.90.3 (disabled)
├── language-go@0.45.3 (disabled)
├── language-markdown@0.25.1
├── language-powershell@4.0.0 (disabled)
├── language-puppet@0.23.0
├── language-typescript@0.3.3 (disabled)
├── linter@2.2.0 (disabled)
├── linter-ansible-linting@1.3.2 (disabled)
├── linter-checkbashisms@0.1.5 (disabled)
├── linter-markdown@5.2.0
├── linter-puppet-lint@0.8.4 (disabled)
├── linter-python@3.1.2
├── linter-shellcheck@1.4.6
├── linter-ui-default@1.7.1
├── lipsum@0.1.0
├── markdown-pdf@2.1.0
├── markdown-preview-plus@2.5.7 (disabled)
├── markdown-scroll-sync@2.1.2
├── markdown-writer@2.7.3
├── metrics@1.2.6 (disabled)
├── overlay-status-icons@0.1.6
├── package-cop@0.2.10
├── project-manager@3.3.5
├── python-debugger@0.2.0
├── python-indent@1.1.5
├── python-nosetests@0.2.0
├── python-tools@0.6.9
├── qolor@0.4.2
├── save-session@0.15.7
├── script@3.17.3
├── ssh-config@0.13.0 (disabled)
├── svn@0.0.13
├── termination@0.6.1
├── todo-show@2.3.0
├── tool-bar@1.1.7
├── tool-bar-atom@1.7.0
├── tool-bar-config@0.1.0
└── zentabs@0.8.9

**Comment by wanderley** [comment] 2018-04-02 20:16
Can you provide more context about this issue? Is there a way to repro it?

From the stacktrace
```
Object.lint - /Users/michael.gracy/.atom/packages/linter-shellcheck/lib/main.js:61:24
```
It seems to be a problem related with `linter-shellcheck`. Can this issue be related with this package?

**Comment by Arcanemagus** [comment] 2018-04-02 20:42
I'm guessing this is a duplicate of https://github.com/AtomLinter/linter-shellcheck/issues/107 and https://github.com/AtomLinter/linter-shellcheck/issues/108 which were fixed... but apparently never released.

I'll push that out right now 😉.

**Closed** 2018-04-03 01:19 UTC
